//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ImovelStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImovelStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcIMO4.Resources.View.Imovel.ImovelStrings", typeof(ImovelStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string apagar {
            get {
                return ResourceManager.GetString("apagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Photo.
        /// </summary>
        public static string apagarfoto {
            get {
                return ResourceManager.GetString("apagarfoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approvals Manager.
        /// </summary>
        public static string aprovacoes {
            get {
                return ResourceManager.GetString("aprovacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Area.
        /// </summary>
        public static string areabruta {
            get {
                return ResourceManager.GetString("areabruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Area.
        /// </summary>
        public static string areadoterreno {
            get {
                return ResourceManager.GetString("areadoterreno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Area.
        /// </summary>
        public static string areautil {
            get {
                return ResourceManager.GetString("areautil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message.
        /// </summary>
        public static string asuamensagem {
            get {
                return ResourceManager.GetString("asuamensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of bedrooms.
        /// </summary>
        public static string bedroomsnumber {
            get {
                return ResourceManager.GetString("bedroomsnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Cart.
        /// </summary>
        public static string cartinvalido {
            get {
                return ResourceManager.GetString("cartinvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string categoria {
            get {
                return ResourceManager.GetString("categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string classse {
            get {
                return ResourceManager.GetString("classse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        public static string concelho {
            get {
                return ResourceManager.GetString("concelho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact can without compromise for more information about the apartment.
        /// </summary>
        public static string contactarsemcompromisso {
            get {
                return ResourceManager.GetString("contactarsemcompromisso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        public static string dataaprovacao {
            get {
                return ResourceManager.GetString("dataaprovacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string datacriacao {
            get {
                return ResourceManager.GetString("datacriacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        public static string dataexpira {
            get {
                return ResourceManager.GetString("dataexpira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string deleted {
            get {
                return ResourceManager.GetString("deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the property.
        /// </summary>
        public static string descricao {
            get {
                return ResourceManager.GetString("descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of the property.
        /// </summary>
        public static string detalhes {
            get {
                return ResourceManager.GetString("detalhes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string distrito {
            get {
                return ResourceManager.GetString("distrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string editar {
            get {
                return ResourceManager.GetString("editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in contact with the advertiser!.
        /// </summary>
        public static string entraremcontacto {
            get {
                return ResourceManager.GetString("entraremcontacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string enviar {
            get {
                return ResourceManager.GetString("enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending Emails.
        /// </summary>
        public static string erromail {
            get {
                return ResourceManager.GetString("erromail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parish.
        /// </summary>
        public static string freguesia {
            get {
                return ResourceManager.GetString("freguesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globalize the description of the property.
        /// </summary>
        public static string globalizardesc {
            get {
                return ResourceManager.GetString("globalizardesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globalize.
        /// </summary>
        public static string globalize {
            get {
                return ResourceManager.GetString("globalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string gravar {
            get {
                return ResourceManager.GetString("gravar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string identidade {
            get {
                return ResourceManager.GetString("identidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Photos.
        /// </summary>
        public static string inserefotos {
            get {
                return ResourceManager.GetString("inserefotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new Ad.
        /// </summary>
        public static string inseririmovel {
            get {
                return ResourceManager.GetString("inseririmovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This subscription has expired, no more ads available .
        /// </summary>
        public static string limitesub {
            get {
                return ResourceManager.GetString("limitesub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the Language.
        /// </summary>
        public static string lingescolha {
            get {
                return ResourceManager.GetString("lingescolha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage my Ads.
        /// </summary>
        public static string managemyads {
            get {
                return ResourceManager.GetString("managemyads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string mensagem {
            get {
                return ResourceManager.GetString("mensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no results.
        /// </summary>
        public static string naoharesultado {
            get {
                return ResourceManager.GetString("naoharesultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string oseuemail {
            get {
                return ResourceManager.GetString("oseuemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string oseunome {
            get {
                return ResourceManager.GetString("oseunome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string pais {
            get {
                return ResourceManager.GetString("pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string pesquisa {
            get {
                return ResourceManager.GetString("pesquisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the errors and try again..
        /// </summary>
        public static string pleasecorrect {
            get {
                return ResourceManager.GetString("pleasecorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your e-mail!.
        /// </summary>
        public static string porfavoremail {
            get {
                return ResourceManager.GetString("porfavoremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a message!.
        /// </summary>
        public static string porfavormensagem {
            get {
                return ResourceManager.GetString("porfavormensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name!.
        /// </summary>
        public static string porfavornome {
            get {
                return ResourceManager.GetString("porfavornome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string preco {
            get {
                return ResourceManager.GetString("preco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ad was created with success, must now wait for approval from the admin.
        /// </summary>
        public static string registogravado {
            get {
                return ResourceManager.GetString("registogravado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one.
        /// </summary>
        public static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Id.
        /// </summary>
        public static string subscricao {
            get {
                return ResourceManager.GetString("subscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent successfully.
        /// </summary>
        public static string sucessomail {
            get {
                return ResourceManager.GetString("sucessomail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Business.
        /// </summary>
        public static string tipodenegocio {
            get {
                return ResourceManager.GetString("tipodenegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Bedrooms.
        /// </summary>
        public static string tipologia {
            get {
                return ResourceManager.GetString("tipologia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Records :.
        /// </summary>
        public static string TotaldeRegistos {
            get {
                return ResourceManager.GetString("TotaldeRegistos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid e-mail!.
        /// </summary>
        public static string validemail {
            get {
                return ResourceManager.GetString("validemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string valor {
            get {
                return ResourceManager.GetString("valor", resourceCulture);
            }
        }
    }
}
