//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LojaSubscricoesStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LojaSubscricoesStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcIMO4.Resources.View.LojaSubscricoes.LojaSubscricoesStrings", typeof(LojaSubscricoesStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        public static string AddtoCart {
            get {
                return ResourceManager.GetString("AddtoCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Ad.
        /// </summary>
        public static string anunciarimovel {
            get {
                return ResourceManager.GetString("anunciarimovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string areyousure {
            get {
                return ResourceManager.GetString("areyousure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnApagar {
            get {
                return ResourceManager.GetString("btnApagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Ads.
        /// </summary>
        public static string ComprarAnuncios {
            get {
                return ResourceManager.GetString("ComprarAnuncios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm that you going to delete the register number.
        /// </summary>
        public static string ConfirmacaoApagar {
            get {
                return ResourceManager.GetString("ConfirmacaoApagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Confirmation.
        /// </summary>
        public static string confirmapagamento {
            get {
                return ResourceManager.GetString("confirmapagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string criar {
            get {
                return ResourceManager.GetString("criar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string data_da_subscricao {
            get {
                return ResourceManager.GetString("data_da_subscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date.
        /// </summary>
        public static string data_expira {
            get {
                return ResourceManager.GetString("data_expira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register was deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Details.
        /// </summary>
        public static string detalhessubs {
            get {
                return ResourceManager.GetString("detalhessubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can create new ads, number of ads by number of months.
        /// </summary>
        public static string Explicaads {
            get {
                return ResourceManager.GetString("Explicaads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Prices.
        /// </summary>
        public static string GerirPrecosAnuncios {
            get {
                return ResourceManager.GetString("GerirPrecosAnuncios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Gravar {
            get {
                return ResourceManager.GetString("Gravar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string identidade {
            get {
                return ResourceManager.GetString("identidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions Index.
        /// </summary>
        public static string LinkVerIndexSubcricoes {
            get {
                return ResourceManager.GetString("LinkVerIndexSubcricoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Expired Subscriptions.
        /// </summary>
        public static string listarexpiradas {
            get {
                return ResourceManager.GetString("listarexpiradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads Store.
        /// </summary>
        public static string lojadeanuncios {
            get {
                return ResourceManager.GetString("lojadeanuncios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register not found .
        /// </summary>
        public static string NaoEncontrado {
            get {
                return ResourceManager.GetString("NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Ads.
        /// </summary>
        public static string NumerodeAnuncios {
            get {
                return ResourceManager.GetString("NumerodeAnuncios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Months.
        /// </summary>
        public static string NumeroMeses {
            get {
                return ResourceManager.GetString("NumeroMeses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string ordens {
            get {
                return ResourceManager.GetString("ordens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string pago {
            get {
                return ResourceManager.GetString("pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string preco {
            get {
                return ResourceManager.GetString("preco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Number of months * .
        /// </summary>
        public static string precopormes {
            get {
                return ResourceManager.GetString("precopormes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euros)+(Number of ads * .
        /// </summary>
        public static string precopormes2 {
            get {
                return ResourceManager.GetString("precopormes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euros).
        /// </summary>
        public static string precopormes3 {
            get {
                return ResourceManager.GetString("precopormes3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (each).
        /// </summary>
        public static string priceeach {
            get {
                return ResourceManager.GetString("priceeach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Cart.
        /// </summary>
        public static string removecart {
            get {
                return ResourceManager.GetString("removecart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew.
        /// </summary>
        public static string renovar {
            get {
                return ResourceManager.GetString("renovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;em&gt;Review&lt;/em&gt; your cart:.
        /// </summary>
        public static string reverocart {
            get {
                return ResourceManager.GetString("reverocart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Deleted.
        /// </summary>
        public static string subapagada {
            get {
                return ResourceManager.GetString("subapagada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Name.
        /// </summary>
        public static string subscriptionname {
            get {
                return ResourceManager.GetString("subscriptionname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Ad subscription.
        /// </summary>
        public static string TituloDaViewCreate {
            get {
                return ResourceManager.GetString("TituloDaViewCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string voltaparalista {
            get {
                return ResourceManager.GetString("voltaparalista", resourceCulture);
            }
        }
    }
}
